config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  root to: 'campaigns#index'
  resources :campaigns do
    resources :todo_lists, except: :index
  end
  resources :comments, only: [:create, :new]
  devise_for :users
  scope '/expert' do
    resources :novices, only: [:index, :edit, :update], controller: 'users', type: 'Novice'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all # permissions for every user, even if not logged in
    return unless user
    can :create, TodoList
    can :create, Comment do |c|
      c.campaign.exists?
    end
    return unless user && user.type == 'Expert'
    can :manage, Campaign
    can :update, Novice
    can :create, Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :expert
  has_many :todo_lists, dependent: :destroy
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :todo_lists, allow_destroy: true

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :title, :commentable_type, :commentable_id, :user_id, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :todo_list
  belongs_to :user
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  belongs_to :campaign
  has_many :todos
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todo_lists
  has_many :todos
  has_many :comments
  enum status: [:qualified, :not_qualified, :banned]
  validates :username, :email, :type, presence: true
  validates :status, presence: true, inclusion: { in: User.statuses }
end

class Expert < User
  has_many :campaigns, dependent: :destroy
  validates :profession, :service, presence: true
end

class Novice < User
  before_save :ensure_expert_fields_nil

  private

  def ensure_expert_fields_nil
    self.profession = nil
    self.service = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_url, :alert => exception.message }
    end
  end


  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :type, :profession, :service)}
      devise_parameter_sanitizer.permit(:sign_out) { |u| u.permit(:username, :email, :password, :type, :profession, :service)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :profession, :service, :status)}
    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @campaigns = Campaign.all
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def new
    @campaign = Campaign.new
    @todo_lists = @campaign.todo_lists
  end

  def show
    @campaign = Campaign.find(params[:id])
    @todo_lists = @campaign.todo_lists
    @comments = @campaign.comments
  end

  def create
    @user = current_user
    @campaign = @user.campaigns.new(campaign_params)
    if @campaign.save
      flash[:success] = "Campaign added!"
      redirect_to @campaign
    else
      flash.now[:danger] = "Invalid information."
      render 'new'
    end
  end

  def update
    @campaign = Campaign.find(params[:id])
    if @campaign.update(campaign_params)
      flash[:success] = "Campaign updated!"
      redirect_to @campaign
    else
      flash.now[:danger] = "Invalid information."
      render 'edit'
    end
  end

  def destroy
    Campaign.find(params[:id]).destroy
    flash[:success] = "Restaurant deleted."
    redirect_to root_path
  end

  private

  def campaign_params
    params.require(:campaign).permit(:title, :tags, :estimated_duration,
                                      todo_lists_attributes:[:id, :title, :_destroy])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    commentable_type = params[:comment][:commentable_type]
    commentable_id = params[:comment][:commentable_id]
    @commentable = commentable_type.constantize.find(commentable_id)
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      flash[:success] = "Comment added!"
      redirect_to parent_campaign
    else
      flash.now[:danger] = "Invalid information."
      render 'new'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:id, :title, :user_id)
  end

  def parent_campaign
    @commentable.instance_of?(Campaign) ? @commentable : @commentable.campaign
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  load_and_authorize_resource

  def show
    @todo_list = TodoList.find(params[:id])
  end

  def create
    @campaign = Campaign.find(params[:campaign_id])
    @todo_list = current_user.todo_lists.new(todo_list_params)
    @todo_list.campaign = @campaign
    if @todo_list.save
      flash[:success] = "Todo List added!"
      redirect_to @campaign
    else
      flash.now[:danger] = "Invalid information."
      render 'new'
    end
  end

  def new
    @campaign = Campaign.find(params[:campaign_id])
    @todo_list = @campaign.todo_lists.new
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:id, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @novices = Novice.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User status changed!"
      redirect_to action: 'index'
    else
      flash.now[:danger] = "Invalid information."
      render 'edit'
    end
  end

  protected
  def user_params
    params.require(:novice).permit(:status, :_update)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/_campaign_form.html.erb
<div class="container" id="form_container">
  <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <h1><%= form_type %> Campaign</h1><br>
          <%= form_for(@campaign) do |f| %>
          <%= f.text_field :title, id: "title", placeholder: "Title", class: "form-control input-sm chat-input"%><br>
          <%= f.text_field :tags, id: "tags", placeholder: "Comma, Seperated, Tags", class: "form-control input-sm chat-input"%><br>
          <%= f.text_field :estimated_duration, id: "estimated_duration", placeholder: "Estimated duration", class: "form-control input-sm chat-input"%><br>
          <%= f.submit "Submit", class: "btn btn-primary btn-md" %>
          <% end %>
      </div>
    </div>
</div>

app/views/campaigns/edit.html.erb
<%= render 'campaign_form', form_type: "Edit" %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Home', root_path %>

app/views/campaigns/index.html.erb
<h1>Campaigns Index</h1>

<% @campaigns.each do |campaign| %>
  <h2><%= link_to campaign.title, campaign %></h2>
  <p>Tags: <%= campaign.tags %></p>
  <p>Created by <%= campaign.expert.username %> </p>

  <% if can? :update, Campaign %>
    <%= link_to "Edit", edit_campaign_path(campaign.id) %>
  <% end %>
<% end %>

app/views/campaigns/new.html.erb
<% provide(:title, "New Campaign") %>
<%= render 'campaign_form', form_type: "New" %>

app/views/campaigns/show.html.erb
<div class="container">
  <div class="col-lg-5 col-lg-offset-3">

    <h1><%= @campaign.title %></h1>
    <p>Tags: <%= @campaign.tags %> </p>
    <p>Estimated duration: <%= @campaign.estimated_duration %> </p>
    <u>Todo Lists</u>
    <% if @todo_lists %>
      <ul><% @todo_lists.each do |t| %>
        <li><%= link_to t.title, [t.campaign, t] %></li>
          <% end %>
      </ul>
    <% end %>
    <%= render partial: 'comments/comments', locals: { commentable: @campaign } %>
    <% if can? :create, Comment %>
      <%= render partial: 'comments/form', locals: { commentable: @campaign } %>
    <% end %>
    <% if can? :update, Campaign %>
      <%= link_to 'Edit', edit_campaign_path(@campaign) %> |
    <% end %>
    <% if can? :delete, Campaign %>
      <%= link_to 'Delete', campaign_path(@campaign), method: :delete %>
    <% end %>
    <% if can? :create, TodoList %>
      <%= link_to 'Add Todo List', new_campaign_todo_list_path(@campaign) %> |
    <% end %>
  </div>
</div>

app/views/comments/_comments.html.erb
<u>Comments</u>
  <ul><% commentable.comments.each do |c| %>
    <li><%= c.title %> (<%= c.user.username %>)</li>
      <% end %>
  </ul>

app/views/comments/_form.html.erb
<%= form_for Comment.new do |f| %>
    <div class="form-group">
      <%= f.text_area :title, class: "form-control", placeholder: "Add a comment" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :commentable_type, value: commentable.class %>
      <%= f.hidden_field :commentable_id, value: commentable.id %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<% if user_signed_in? %>
  <%= link_to 'Log out', destroy_user_session_path, method: :get %>
  <% if can? :create, Campaign %>
    <%= link_to 'Create campaign', new_campaign_path %>
  <% end %>
  <% if can? :update, Novice %>
    <%= link_to 'Authorize Novice users', novices_path %>
  <% end %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Log in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campaigns</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/todo_lists/_todo_list_form.html.erb
<div class="container" id="form_container">
  <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <h1><%= form_type %> Todo List</h1><br>
          <%= form_for [@campaign, TodoList.new]  do |f| %>
            <%= f.text_field :title, id: "title", placeholder: "Title", class: "form-control input-sm chat-input"%><br>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit "Submit", class: "btn btn-primary btn-md" %>
          <% end %>
        </div>
    </div>
</div>

app/views/todo_lists/new.html.erb
<% provide(:title, "New Todo List") %>
<%= render 'todo_list_form', form_type: "New" %>

app/views/todo_lists/show.html.erb
<div class="container">
  <div class="col-lg-5 col-lg-offset-3">

    <h1><%= @todo_list.title %></h1>
    <p>For: <%= @todo_list.campaign.title %> </p>
    <u>Todos</u>
      <ul><% @todo_list.todos.each do |t| %>
        <li><%= t.title %></li>
          <% end %>
      </ul>

    <%= render partial: 'comments/comments', locals: { commentable: @todo_list } %>
    <% if can? :create, Comment %>
      <%= render partial: 'comments/form', locals: { commentable: @todo_list } %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container" id="form_container">
  <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <h1>Edit User</h1><br>

          <%= form_for(@user) do |f| %>

            <div class="field">
              <%= f.radio_button(:status, "qualified") %>
              <%= f.label(:status, "qualified") %>
              <%= f.radio_button(:status, "not_qualified") %>
              <%= f.label(:status, "not_qualified") %>
              <%= f.radio_button(:status, "banned") %>
              <%= f.label(:status, "banned") %>
            </div>

            <div class="actions">
              <%= f.submit "Update" %>
            </div>
          <% end %>
      </div>
    </div>
</div>

app/views/users/index.html.erb
<h1>All novices</h1>
<ul>
  <% @novices.each do |novice| %>
    <li><%= novice.username %></li>
    <li><%= novice.email %></li>
    <li><%= novice.type %></li>
    <li><%= novice.status %></li>
    <li><%= novice.created_at %></li>
    <%= link_to 'Edit novice\'s status', edit_novice_path(novice) %><br><br>
  <% end %>
</ul>